<a href="https://colab.research.google.com/github/Ayan282/colab/blob/main/statistika3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import files
uploaded=files.upload()

Saving Data (2).xlsx to Data (2).xlsx

In [4]:
import pandas as pd
df = pd.read_excel("Data (2).xlsx")

In [5]:
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df

,Student_ID,Gender,Age,Department,Education_Level,Region,Height,Weight,Exam_Score,Salary,Product_Category,Sales
0,1,Male,20,IT,Bachelor,Baku,175,70,78,800,Electronics,1200
1,2,Female,22,Finance,Bachelor,Ganja,165,58,85,750,Clothing,900
2,3,Male,21,IT,Bachelor,Baku,180,80,90,900,Electronics,1500
3,4,Female,23,Marketing,Master,Sumqayit,168,60,72,700,Beauty,600
4,5,Male,24,Finance,Master,Baku,172,75,88,950,Electronics,2000
5,6,Female,20,IT,Bachelor,Ganja,160,55,91,780,Clothing,850
6,7,Male,22,Marketing,Bachelor,Baku,178,82,65,650,Food,400
7,8,Female,21,Finance,Bachelor,Sumqayit,162,57,79,720,Beauty,500
8,9,Male,23,IT,Master,Baku,185,90,84,1000,Electronics,2500
9,10,Female,24,Marketing,Master,Ganja,170,63,92,1100,Clothing,1300
10,11,Male,22,Finance,Bachelor,Baku,176,77,73,680,Food,450
11,12,Female,21,IT,Bachelor,Sumqayit,164,59,87,820,Electronics,1600
12,13,Male,25,Marketing,PhD,Baku,182,85,95,1500,Electronics,3000
13,14,Female,23,Finance,Master,Ganja,166,61,81,900,Beauty,700
14,15,Male,20,IT,Bachelor,Baku,174,72,69,600,Food,350
15,16,Female,22,Marketing,Bachelor,Sumqayit,169,64,76,740,Clothing,950
16,17,Male,24,Finance,Master,Baku,177,79,89,980,Electronics,2200
17,18,Female,21,IT,Bachelor,Ganja,161,56,93,860,Beauty,650
18,19,Male,23,Marketing,Master,Baku,183,88,71,690,Food,500
19,20,Female,25,Finance,PhD,Baku,167,62,97,1600,Electronics,3200

In [ ]:
df["Gender"].count()
a=df.loc[df["Gender"]=="Male"]
a['Gender'].count()
ehtimalmale=a['Gender'].count()/df["Gender"].count()
print(ehtimalmale)

0.5

In [ ]:
b=df.loc[df["Gender"]=="Female"]
b["Gender"].count()
ehtimalfemale=a['Gender'].count()/df["Gender"].count()
print(ehtimalfemale)

0.5

In [ ]:
c=df.loc[df["Department"]=="IT"]
c["Department"].count()
ehtimalit=c["Department"].count()/df["Gender"].count()
ehtimalit

np.float64(0.35)

In [ ]:
x=ehtimalmale+ehtimalfemale
x

np.float64(1.0)

In [ ]:
e=df.loc[df["Exam_Score"]>80]
e["Exam_Score"].count()
df["Exam_Score"].count()
ehtimalscore=e["Exam_Score"].count()/df["Exam_Score"].count()
ehtimalscore

np.float64(0.6)

In [ ]:
p=df.loc[df["Gender"]=="Female"]
p["Gender"].count()
b=df[(df["Gender"]=="Female")& (df["Exam_Score"]>80)]
b["Gender"].count()
eht=b["Gender"].count()/p["Gender"].count()
eht

np.float64(0.7)

In [ ]:
df["Department"]=="IT"
df["Department"].count()

np.int64(20)

In [ ]:
f=df[(df["Department"]=="IT")& (df["Exam_Score"]>80)]
ehtimall=f["Department"].count()/df["Department"].count()
print(ehtimall)

0.25

In [ ]:
g=df[(df["Gender"]=="Male")& (df["Exam_Score"]>80)]
g['Gender'].count()
kesisme=g['Gender'].count()/df['Gender'].count()
kesisme

np.float64(0.25)

In [ ]:
a=df[df["Gender"]=="Male"]
a["Gender"].count()
df["Gender"].count()
A=a["Gender"].count()/df["Gender"].count()
A

np.float64(0.5)

In [ ]:
b=df[df["Exam_Score"]>80]
b["Exam_Score"].count()
df["Exam_Score"].count()
B=b["Exam_Score"].count()/df["Exam_Score"].count()
B

np.float64(0.6)

In [ ]:
hasil=A*B
hasil

np.float64(0.3)

hasil ve kesisme ferqli olduguna gore ehtimallar independentdir ehtimallarin bas vermesi bir-birine tesir etmir

In [7]:
A=df[(df["Department"]=="IT")&(df['Exam_Score']>80)]
A["Department"].count()
B=df[df["Department"]=="IT"]
B["Department"].count()
P1=A["Department"].count()/B["Department"].count()
P1

np.float64(0.7142857142857143)

In [8]:
A=df[(df["Exam_Score"]>80)&(df["Department"]=="IT")]
A['Exam_Score'].count()
B=df[df["Exam_Score"]>80]
B['Exam_Score'].count()
P2=A['Exam_Score'].count()/B['Exam_Score'].count()
P2

np.float64(0.4166666666666667)

In [10]:
p2=((P2)*(B["Department"].count()))/B['Exam_Score'].count()
p2

np.float64(0.4166666666666667)

In [14]:
h=df[(df["Department"]=="Finance")&(df['Exam_Score']>80)]
h["Department"].count()
d=df[df["Department"]=="Finance"]
d["Department"].count()
ehtimalll=h["Department"].count()/d["Department"].count()
ehtimalll

np.float64(0.7142857142857143)

In [19]:
df["Level_Score"]=pd.cut(df['Exam_Score'],bins=[0,70,85,97],labels=["Low","Medium","High"])
df["Level_Score"]

0     Medium
1     Medium
2       High
3     Medium
4       High
5       High
6        Low
7     Medium
8     Medium
9       High
10    Medium
11      High
12      High
13    Medium
14       Low
15    Medium
16      High
17      High
18    Medium
19      High
Name: Level_Score, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

In [23]:
q=df[(df["Level_Score"])=="Low"]
q["Level_Score"].count()
df["Level_Score"].count()
Plow=q["Level_Score"].count()/df["Level_Score"].count()
Plow

np.float64(0.1)

In [25]:
q=df[(df["Level_Score"])=="Medium"]
q["Level_Score"].count()
df["Level_Score"].count()
Pmedium=q["Level_Score"].count()/df["Level_Score"].count()
Pmedium

np.float64(0.45)

In [26]:
df[(df["Level_Score"])=="High"]
q["Level_Score"].count()
df["Level_Score"].count()
Phigh=q["Level_Score"].count()/df["Level_Score"].count()
Phigh

np.float64(0.45)

In [27]:
Phigh+Pmedium+Plow

np.float64(1.0)

In [29]:
Low = 1
Medium = 2
High = 3
expected_value=Phigh*High+Pmedium*Medium+Plow*Low
expected_value

np.float64(2.35)